# Generated by Django 4.2.6 on 2023-11-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_logged', models.DateTimeField(auto_now_add=True)),
                ('next_hearing', models.DateTimeField()),
                ('lawyer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
