# Generated by Django 4.2.6 on 2023-11-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_lawyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_description',
            new_name='case_desc',
        ),
    ]
