# Generated by Django 4.2.6 on 2023-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_case_case_desc_remove_case_case_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
