# Generated by Django 4.2.6 on 2023-11-23 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearingDate', models.DateField(blank=True, null=True)),
                ('judgmentDate', models.DateField(blank=True, null=True)),
                ('submissionDate', models.DateField(blank=True, null=True)),
                ('mentionDate', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='lawyer',
        ),
        migrations.AddField(
            model_name='case',
            name='instrutions_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CaseDates',
        ),
        migrations.AddField(
            model_name='casedatehistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_histories', to='cases.case'),
        ),
    ]
