# Generated by Django 4.2.6 on 2023-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_loggedby_alter_case_instrutions_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedatehistory',
            name='hearingDate',
        ),
        migrations.RemoveField(
            model_name='casedatehistory',
            name='judgmentDate',
        ),
        migrations.RemoveField(
            model_name='casedatehistory',
            name='mentionDate',
        ),
        migrations.RemoveField(
            model_name='casedatehistory',
            name='submissionDate',
        ),
        migrations.RemoveField(
            model_name='casedatehistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='casedatehistory',
            name='date_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casedatehistory',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
    ]
